# Generated by Django 2.1.4 on 2019-04-29 12:29

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('locker', '0002_auto_20190207_0614'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Lockers',
            new_name='Locker',
        ),
    ]
