# Generated by Django 2.1.5 on 2019-06-17 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locker', '0002_locker_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='locker',
            name='created_at',
        ),
    ]
